In [2]:
import torch 
from NN import *
import torch.nn as nn




In [62]:
ex_matrix = torch.tensor([[1, 2, 9], [1, 6, 3], [7, 0, 9], 
                          [1, 5, 0], [2, 4, 3], [1, 1, 1], 
                          ], dtype=torch.float32)

print(ex_matrix.shape)
print(ex_matrix.unsqueeze(0).shape)



torch.Size([6, 3])
torch.Size([1, 6, 3])


In [63]:
a = NNT(ex_matrix, (5, 3))
print(a.prime.shape)
print(a.prime)


torch.Size([1, 30, 3])
tensor([[[1., 2., 9.],
         [7., 0., 9.],
         [2., 4., 3.],
         [1., 6., 3.],
         [1., 1., 1.],
         [1., 6., 3.],
         [2., 4., 3.],
         [1., 5., 0.],
         [1., 1., 1.],
         [1., 2., 9.],
         [7., 0., 9.],
         [1., 2., 9.],
         [2., 4., 3.],
         [1., 1., 1.],
         [1., 6., 3.],
         [1., 5., 0.],
         [1., 6., 3.],
         [2., 4., 3.],
         [1., 1., 1.],
         [1., 2., 9.],
         [2., 4., 3.],
         [1., 6., 3.],
         [1., 5., 0.],
         [1., 1., 1.],
         [1., 2., 9.],
         [1., 1., 1.],
         [2., 4., 3.],
         [1., 5., 0.],
         [1., 6., 3.],
         [1., 2., 9.]]])


In [64]:
conv2d_layer = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = a.kernel_shape, stride = a.num_closest)

In [65]:
output = conv2d_layer(a.prime)
print(output.shape)
print(output)

torch.Size([1, 6, 1])
tensor([[[5.4218],
         [5.1074],
         [5.9157],
         [4.3280],
         [5.1100],
         [4.1780]]], grad_fn=<SqueezeBackward1>)


In [66]:
a_prime = a.prime.squeeze(1).permute((0, 2, 1))
print(a_prime.shape)

torch.Size([1, 3, 30])


In [67]:
conv1d_layer = nn.Conv1d(in_channels = 3, out_channels = 1, kernel_size = 3, stride = 3)
output = conv1d_layer(a_prime)
print(output.shape)
print(output)

torch.Size([1, 1, 10])
tensor([[[ 1.9127, -2.2228,  0.0816,  0.6080, -1.5441, -1.9980, -0.5699,
          -0.5971,  0.7561, -3.3027]]], grad_fn=<ConvolutionBackward0>)


In [4]:
m = nn.Conv1d(16, 33, 3)
input = torch.randn(20, 16, 50)
output = m(input)
print(output.shape)
print(m.weight.shape)

torch.Size([20, 33, 48])
torch.Size([33, 16, 3])


In [69]:
input.shape

torch.Size([20, 16, 50])

In [70]:
ex_matrix = torch.tensor([[1, 2, 9], [1, 6, 3], [7, 0, 9], 
                          [1, 5, 0], [2, 4, 3], [1, 1, 1], 
                          ], dtype=torch.float32)

list_matrix = [ex_matrix, ex_matrix, ex_matrix]

stack = torch.stack(list_matrix, dim = 0)
print(stack.shape)

torch.Size([3, 6, 3])


# Example

In [71]:
b = torch.zeros(stack.shape[0], stack.shape[1], stack.shape[1])
print(b.shape)

torch.Size([3, 6, 6])


In [72]:
import torch

matrix = torch.randint(0, 10, (3, 6, 3), dtype=torch.float32)
print(matrix)
print(matrix.shape)

tensor([[[5., 4., 8.],
         [1., 0., 9.],
         [5., 6., 0.],
         [4., 1., 9.],
         [7., 0., 6.],
         [7., 8., 4.]],

        [[0., 8., 8.],
         [3., 7., 1.],
         [1., 2., 7.],
         [4., 6., 4.],
         [7., 3., 9.],
         [6., 7., 2.]],

        [[1., 6., 2.],
         [1., 8., 5.],
         [7., 8., 1.],
         [0., 5., 2.],
         [7., 1., 0.],
         [6., 4., 1.]]])
torch.Size([3, 6, 3])


In [73]:
matrix[0,]


tensor([[5., 4., 8.],
        [1., 0., 9.],
        [5., 6., 0.],
        [4., 1., 9.],
        [7., 0., 6.],
        [7., 8., 4.]])

In [74]:
a = torch.zeros(3, 6, 6)

for i in range(matrix.shape[0]): 
    for j in range(matrix.shape[1]): 
        for k in range(matrix.shape[1]): 
            a[i, j, k] = torch.norm(matrix[i, j] - matrix[i, k])
            


In [75]:
print(a.size())
print(a)

torch.Size([3, 6, 6])
tensor([[[ 0.0000,  5.7446,  8.2462,  3.3166,  4.8990,  6.0000],
         [ 5.7446,  0.0000, 11.5326,  3.1623,  6.7082, 11.1803],
         [ 8.2462, 11.5326,  0.0000, 10.3441,  8.7178,  4.8990],
         [ 3.3166,  3.1623, 10.3441,  0.0000,  4.3589,  9.1104],
         [ 4.8990,  6.7082,  8.7178,  4.3589,  0.0000,  8.2462],
         [ 6.0000, 11.1803,  4.8990,  9.1104,  8.2462,  0.0000]],

        [[ 0.0000,  7.6811,  6.1644,  6.0000,  8.6603,  8.5440],
         [ 7.6811,  0.0000,  8.0623,  3.3166,  9.7980,  3.1623],
         [ 6.1644,  8.0623,  0.0000,  5.8310,  6.4031,  8.6603],
         [ 6.0000,  3.3166,  5.8310,  0.0000,  6.5574,  3.0000],
         [ 8.6603,  9.7980,  6.4031,  6.5574,  0.0000,  8.1240],
         [ 8.5440,  3.1623,  8.6603,  3.0000,  8.1240,  0.0000]],

        [[ 0.0000,  3.6056,  6.4031,  1.4142,  8.0623,  5.4772],
         [ 3.6056,  0.0000,  7.2111,  4.3589, 10.4881,  7.5498],
         [ 6.4031,  7.2111,  0.0000,  7.6811,  7.0711,  4.1231],