In [1]:
import torch 
from NNT import *
import torch.nn as nn



tensor([[[[2., 1., 3.],
          [1., 0., 2.],
          [5., 2., 1.],
          [2., 1., 3.],
          [1., 0., 2.],
          [2., 1., 3.],
          [4., 6., 5.],
          [5., 2., 1.]]]])
torch.Size([1, 1, 8, 3])


In [2]:
ex_matrix = torch.tensor([[1, 2, 9], [1, 6, 3], [7, 0, 9], 
                          [1, 5, 0], [2, 4, 3], [1, 1, 1], 
                          ], dtype=torch.float32)

a = NNT(ex_matrix, (2, 3))
print(a.convolution_matrix.shape)
print(a.convolution_matrix)


tensor([[[[1., 2., 9.],
          [7., 0., 9.],
          [1., 6., 3.],
          [2., 4., 3.],
          [7., 0., 9.],
          [1., 2., 9.],
          [1., 5., 0.],
          [1., 6., 3.],
          [2., 4., 3.],
          [1., 6., 3.],
          [1., 1., 1.],
          [2., 4., 3.]]]])
torch.Size([1, 1, 12, 3])


In [9]:
conv2d_layer = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = a.kernel_shape, stride = a.num_closest)

In [10]:
output = conv2d_layer(a.convolution_matrix)
print(output.shape)
print(output)

torch.Size([1, 1, 6, 1])
tensor([[[[-3.7231],
          [-2.9690],
          [-4.0512],
          [-1.6924],
          [-2.3229],
          [-0.7290]]]], grad_fn=<ConvolutionBackward0>)
